### ISSUE TITLE
नकारोत्तरः उकारः उच्चारणार्थः

### ISSUE THREAD

**Issue by sridharb1** [ashtadhyayi-com/data-edit#371]
There are many examples of this usage. This particular one is from इदितो नुम् धातोः ७.१.५८

The actual आगमः is नुँम् where the deletion of the उँ is easily explained by १.३.२ उपदेशेऽजनुनासिक इत् instead of telling उच्चारणार्थः

Wouldn't it be more complete for a reference-level website like yours to use the latter usage, i.e. use नुँम् and be able to easily derive न् instead of saying नकारोत्तरः उकारः उच्चारणार्थः?

Please explain if I am mistaken.

Thanks,
Sridhar

**Comment by neeleshb** [comment]
The आगम is नुम्, not नुँम् ।  The उ of नुम् is not इत्संज्ञक because there is no prayojana of making it इत्संज्ञक.

**Comment by sridharb1** [comment]
Consider अचि श्नुधातुभ्रुवां य्वोरियङुवङौ ६.४.७७.

The two pictures are from the भैमी व्याख्यानम् प्रथमः भागः, पृष्ठसङ्ख्या २५६

Consider also 
[https://avg-sanskrit.org/2011/07/19/स्तुवन्ति-3ap-लँट्/](url)

In both places, the सूत्रम् itself is य्वोरियँङुवँङौ and the आदेशै इयँङ्, उवँङ् च स्तः

Please consider the प्रक्रिया from your website for the same सूत्रम् as an example (attached) where again, the उच्चारणार्थः paradigm is used.

As another example, I have attached my प्रक्रिया from ईकारान्तः पुंलिङ्गः नी-शब्दः चतुर्थीविभक्तिः एकवचनम् to show how १.३.२ उपदेशेऽजनुनासिक इत् is used to make इयँङ् to इय्

धन्यवादः
श्रीधरः

![ईकारान्तः पुंलिङ्गः नी-शब्दः चतुर्थीविभक्तिः एकवचनम्](https://github.com/ashtadhyayi-com/data-edit/assets/13346687/e624a76a-602d-4464-b4fc-98087a434f22)


![IMG_E5702](https://github.com/ashtadhyayi-com/data-edit/assets/13346687/2d9f9c18-7ee9-460f-b4c0-e7573de46ca4)
![IMG_E5703](https://github.com/ashtadhyayi-com/data-edit/assets/13346687/34bce55e-fe43-4b78-a864-1eeb1054960c)
![उवँङ्](https://github.com/ashtadhyayi-com/data-edit/assets/13346687/4dc88837-5a47-44e5-a77f-0121ee11cd44)

**Comment by neeleshb** [comment]
Please note, all the references you have quoted are incorrect. Unless there is a prayojana of something making इत्संज्ञक, it cannot be called इत्संज्ञक. 
उँ is इत्संज्ञक in pratyayas like क्तवतुँ and वतुँप्, but not in प्रत्ययs like तुमुन् or नुम् । 
I am closing this thread. If you have any further questions, please write to me directly.
